### ISSUE TITLE
Get Token_access failing

### ISSUE THREAD

**Issue by mattdoub** [SaxoBank/openapi-samples-js#2]
Hello,

Thx vm for thoses samples. very useful.
In **OAuth2 Code Flow example**
After redirect, get_code works fine but get_token fails with the following error:
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

Any idea why? 
PS: I've used the live gateway in this test with correct Appkeys and links

**Comment by gidven** [comment]
Hi Matt,

The samples were tested in SIM only at this point. I think the URL you are trying to access does not exist (which yields a 404 with HTML body). When this body is being parsed, JSON fails because it gets a HTML open bracket `<`.

I will put an item on our to-do list to update the samples for both environment. For now you can check the URL that is used for the get_token function and make sure it is the LIVE one instead of SIM. URLs can be found here: https://www.developer.saxo/openapi/learn/environments
